appName: alpine

namespace: 11877-deploymentapp

replicaCount: 1

image:
  repository: munialluri/rajalakshmialpine
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources: {}

configmap:
  name: alpine-configmap
  data:
    CUSTOM_MESSAGE: "Welcome to Alpine App!"
